### ISSUE TITLE
password - time limit override

### ISSUE THREAD

**Issue by mshurmer** [mcogoni/supersdr#10]
I  issue the following command  to start (password changed below)

Connection is stated ok and rigctld  work as expected but the timelimit override password does not work - it times out

supersdr.py -w xxxxxxxx --kiwiserver vk6qs.proxy.kiwisdr.com --kiwiport 8073 -S 127.0.0.1 -P 4532

On the same kiwi this http  works fine

http://vk6qs.proxy.kiwisdr.com:8073/?password=xxxxxxxx

**Comment by mcogoni** [comment]
Thanks, I'll look into it.

**Comment by mcogoni** [comment]
OK, it should work now.
Please let me know.

marco

**Comment by mshurmer** [comment]
That got it - well done.  Hope its ok to give feedback as I use the software  :)

**Comment by mcogoni** [comment]
Thanks!
Of course your feedback is more than welcome.

73,
marco

Il giorno mer 2 giu 2021 alle ore 15:23 mshurmer
***@***.***> ha scritto:
>
> That got it - well done. Hope its ok to give feedback as I use the software :)
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
marco cogoni
CRS4
http://sibamanna DOT duckdns DOT org
