### ISSUE TITLE
New useful features

### ISSUE THREAD

**Issue by Strato75** [mcogoni/supersdr#3]
Hi, 
I'm using the SDR with the new features and it looks fantastic. I don't wanna bother you, but I think that some other features could be useful and can increase definitely the donation rate :-).
I identified these most important ones (in my opinion):
- make the filter passband variable
- show the current frequency of the mouse pointer
- enabling the mouse wheel for zooming

Thank you again,
Bye
Giovanni

**Comment by mcogoni** [comment]
I think that all features have been implemented.
Let me know if it suits you or you'd like to have some coffee too.

bye,
marco
